### ISSUE TITLE
Error when running: java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics 

### ISSUE THREAD

**Issue by alexander-myltsev** [wuhewuhe/bybit-java-api#58]
Hi. I'm adding dependency to my sbt config of a Scala project as follows:
```
libraryDependencies += "io.cifrum" % "bybit-java-api" % "1.2.5"
```

And then I'm getting the error when trying to run the project:
```
[main] INFO com.bybit.api.client.websocket.impl.WebsocketStreamClientImpl - wss://stream.bybit.com/v5/public/linear
[ERROR] Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
[ERROR] 	at okhttp3.Request$Builder.url(Request.kt)
[ERROR] 	at com.bybit.api.client.websocket.httpclient.WebSocketStreamHttpClientSingleton.createWebSocket(WebSocketStreamHttpClientSingleton.java:34)
[ERROR] 	at com.bybit.api.client.websocket.impl.WebsocketStreamClientImpl.connect(WebsocketStreamClientImpl.java:278)
[ERROR] 	at com.bybit.api.client.websocket.impl.WebsocketStreamClientImpl.getPublicChannelStream(WebsocketStreamClientImpl.java:290)
[ERROR] Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
[ERROR] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
[ERROR] 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
[ERROR] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[ERROR] 	... 6 more
 ... finished with exit code 1
```

I've kind of fixed it by adding `"com.squareup.okio" % "okio" % "3.9.0"`. How do you recommend to fix it?

**Comment by VictorFrWu** [comment]
if you build by sbt please use 
**libraryDependencies += "io.github.wuhewuhe" % "bybit-java-api" % "1.2.7"**
